
#Config for PattysMoreStuff
[pattysmorestuff]
	#Determines what block the game will generate mining return portals out of
	#Use the block tag pattysminingdimension:mining_portal_frame_blocks to determine what blocks portals can be built with
	#If value entered here is not a valid block it will default to generating pattysminingdimension:mining_portal_frame
	ReturnMiningPortalFrameBlockID = "pattysminingdimension:mining_portal_frame"

